name: nsound
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  rxdart: ^0.28.0
  permission_handler: ^11.3.1
  on_audio_query: ^2.9.0
  package_info_plus: ^8.2.1
  marquee: ^2.3.0
  lottie: ^3.3.1
  just_audio_background: ^0.0.1-beta.15
  just_audio: ^0.9.46
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  get_it: ^8.0.3
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.17
  flutter_staggered_animations: ^1.1.1
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/icon/sound.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/lottie/
    - assets/images/
    - assets/svg/
